dist: trusty

matrix:
  include:
    - language: java
      jdk: openjdk8
      env:
        - FRONT=false
        - NODE_VERSION="6.10.1"
    - language: node_js
      node_js: $NODE_VERSION
      env:
        - FRONT=true
        - NODE_VERSION="6.10.1"

before_install:
  - nvm install $NODE_VERSION
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - if [[ $FRONT = 'true' ]]; then cd front; fi
