dist: trusty

env:
  global:
    - NODE_VERSION="6.10.1"

matrix:
  include:
    - language: java
      jdk: openjdk8
      env: FRONT=false

    - language: node_js
      node_js: $NODE_VERSION
      env: FRONT=true

before_install:
  - nvm install $NODE_VERSION
  - if [[ $FRONT = 'true' ]]; then cd front; fi
