dist: trusty

matrix:
  include:
    - language: java
      jdk: openjdk8
      env: FRONT=false

    - language: node_js
      node_js:
        - lts/*
        - node
      env: FRONT=true

before_install:
  - if [[ $FRONT = 'true' ]]; then cd front; fi
