matrix:
  include:
    - language: java
      jdk: openjdk8
      env: FRONT=false

    - language: node_js
      node_js: lts/*
      env: FRONT=true

    - language: node_js
      node_js: node
      env: FRONT=true

before_install:
  - if [[ $FRONT = 'true' ]]; then cd front; fi
