sudo: required
matrix:
  include:
    - language: java
      jdk: openjdk8
      env: FRONT=false

    - language: java
      jdk: oraclejdk8
      env: FRONT=false

    - language: java
      jdk: openjdk9
      env: FRONT=false

    - language: java
      jdk: oraclejdk9
      env: FRONT=false

    - language: java
      jdk: openjdk10
      env: FRONT=false

    - language: java
      jdk: oraclejdk10
      env: FRONT=false

    - language: node_js
      node_js: lts/*
      env: FRONT=true

    - language: node_js
      node_js: node
      env: FRONT=true

  allow_failures:
    - jdk: openjdk9
    - jdk: oraclejdk9
    - jdk: openjdk10
    - jdk: oraclejdk10

before_install:
  - if [[ $FRONT = 'true' ]]; then cd front; fi
